version: "3.5"

services:
  database:
    container_name: postgres12.2
    image: postgres:12.2
    ports:
      - "5488:5432/tcp"
    networks:
      - postgres
    volumes:
      - dbvolume:/var/lib/postgresql/data/pgdata
    environment:
      - TZ=America/Asuncion
      - PGTZ=America/Asuncion
      - POSTGRES_USER=changeme
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=changeme
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always